命令稿啟動於 西元2017年03月10日 (週五) 14時35分02秒
]0;nckucsie@sa-csie-ncku-edu-tw:~/test/lab1[?1034h[nckucsie@sa-csie-ncku-edu-tw lab1]$ g==[K[K++ -o lab1 naim[K[K[K[Kmain.cpp
]0;nckucsie@sa-csie-ncku-edu-tw:~/test/lab1[nckucsie@sa-csie-ncku-edu-tw lab1]$ ./ [K [Klab1
44
22
11
34
17
52
26
13
40
20
10
5
16
8
4
2
1
]0;nckucsie@sa-csie-ncku-edu-tw:~/test/lab1[nckucsie@sa-csie-ncku-edu-tw lab1]$ 33
bash: 33: 找不到指令...
]0;nckucsie@sa-csie-ncku-edu-tw:~/test/lab1[nckucsie@sa-csie-ncku-edu-tw lab1]$ 33./lab14[K
33
100
50
25
76
38
19
58
29
88
44
22
11
34
17
52
26
13
40
20
10
5
16
8
4
2
1
]0;nckucsie@sa-csie-ncku-edu-tw:~/test/lab1[nckucsie@sa-csie-ncku-edu-tw lab1]$ exit

命令稿已於 西元2017年03月10日 (週五) 14時36分37秒
 完成